### ISSUE TITLE
:key: Créer comptes APIGEE

### ISSUE THREAD

**Issue by adriens** [adriens/temps-attente-streamlit#10]
# :dart: Actions

- [x] lire et comprendre [🔑 APIGEE 101: onboarding & authentication](https://dev.to/optnc/apigee-101-onboarding-authentication-1ghl)
- [x] Regarder et comprendre [APIGEE OPT - onboarding portail](https://www.youtube.com/watch?v=L56z2Vkht5E)
- [x] Chaque développeur se crée ses propres clés
- [x] Chaque développeur valide un appel REST via [`httpie`](https://httpie.io/docs/cli), en ligne de commande

**Comment by MalcolmBrt** [comment]
C'est fait de mon côté :
![image](https://github.com/user-attachments/assets/e928b65c-6ee4-4084-9e2d-8a38fe219ebb)
C'est une clé test, je l'ai révoquée.
@morgancarre tu pourras le faire également stp

**Comment by adriens** [comment]
Joli @MalcolmBrt :clap: 

:point_right: Pense à mettre en texte ta commande `hhtpie` comme ça ça documente pour @morgancarre : i lgagnera du temps.

:bulb: Tu peux aussi stocker ton secret dans ta session et comme ça t peux copier ta commande sans avoir à afficher ton secret : https://httpie.io/docs/cli/sessions

**Comment by MalcolmBrt** [comment]
Voici la commande :
`http GET https://api.opt.nc/temps-attente-agences/agences x-apikey:[clé api] commune==[commune]`

**Comment by adriens** [comment]
:bulb: Tip pour améliorer la qualité des commentaires, check comment n'intègre un script shell : 

```shell
http GET https://api.opt.nc/temps-attente-agences/agences x-apikey:[clé api] commune==[commune]
```

Ensuite tu peux stocket ta variable dans une session , comme ça tu n'as même plus besoin de la nommer, et ça se fait via les [session](https://httpie.io/docs/cli/sessions)

**Comment by adriens** [comment]
Oubliez pas de tenir à jour l'avancement en cochant : 

![image](https://github.com/user-attachments/assets/e53f0948-cf42-43f3-aa6d-f9859699817f)

**Comment by MalcolmBrt** [comment]
Ok je viens d'essayer avec les sessions
![image](https://github.com/user-attachments/assets/3db29802-8417-4d63-a08a-42eda81c23db)

**Comment by adriens** [comment]
:clap: @MalcolmBrt : t'as vu comme c super clean du coup ?
Btw :point_down:  
![image](https://github.com/user-attachments/assets/935fb3a4-65e3-489e-a688-c23b3332b082)

**Comment by morgancarre** [comment]
Voici ma commande (avec la session) :
 
![image](https://github.com/user-attachments/assets/c6f3819e-c138-422b-9b39-bcf70db5a34b)

**Comment by adriens** [comment]
top @morgancarre , c'est cet endpoint que vous pourrez utiliser pour construire la liste déroulante de choix de l'agence :+1:

**Comment by adriens** [comment]
:100: :ok: 
![image](https://github.com/user-attachments/assets/874961d4-9873-4028-99ea-53985c68b667)
