### ISSUE TITLE
:bar_chart:  Première page dynamique

### ISSUE THREAD

**Issue by adriens** [adriens/temps-attente-streamlit#11]
Implémenter : 

- [x] #21
- [x] Cliquer sur une agence
- [x] #22
- [x] Auto-refresh de la page
- [x] #23

**Comment by adriens** [comment]
@MalcolmBrt , pour inspiration, bien stylé et avec u thème dark, cf [tweet](https://x.com/thedataprof/status/1838658228777030039/photo/1)

![image](https://github.com/user-attachments/assets/96fd002b-9086-4ca8-85e7-f9ea76e2fadb)

**Comment by MalcolmBrt** [comment]
Faut il diviser cette issue en plusieurs plus petite issue @adriens ?

**Comment by adriens** [comment]
Tu pourrais oui, mais pas forcément chaque sous-tâche. 
grosso modo, voila comment tu pourrais les générer : 
![image](https://github.com/user-attachments/assets/99a6e7da-1d53-4ca4-a4fd-9077dccc4a3c)

Pour générer, il suffit de cliquer que le bouton rond qui apparaît en fin de ligne.

Un bon facteur de choix pour couper ou non c'est par exemple pour divier efficacement le travail pour plusieurs personnes.

**Comment by adriens** [comment]
C good ?

**Comment by MalcolmBrt** [comment]
Oui merci

**Comment by adriens** [comment]
> Oui merci

En effet, je vois c'est 🆗 👍 
![image](https://github.com/user-attachments/assets/a02e06b3-b523-4447-9d0c-6dd4ac2ba5d3)

**Comment by adriens** [comment]
✋ Surtout, oublie pas de charger le secret de ton API Key dans une variable d'environnement... que tu devrais aller choper depuis Python genre [`os.env`](https://www.geeksforgeeks.org/python-os-environ-object/)

```python
# importing os module  
import os 
import pprint 
  
# Get the list of user's 
env_var = os.environ 
  
# Print the list of user's 
print("User's Environment variable:") 
pprint.pprint(dict(env_var), width = 1) 
```

**Comment by MalcolmBrt** [comment]
Puisque cette issue a été complété, on peut peut-être passé à la v1.0 ?

**Comment by adriens** [comment]
> Puisque cette issue a été complété, on peut peut-être passé à la v1.0 ?

Chiche
Let'go

**Comment by adriens** [comment]
> Puisque cette issue a été complété, on peut peut-être passé à la v1.0 ?

La nouvelle milestone v1.0 a été lancée mais la précédente n'a pas été terminée : on doit d'abord finir ce qui est entamé : 
![image](https://github.com/user-attachments/assets/89407837-cb15-467c-9c5a-9d90a7dce5ef)

**Comment by adriens** [comment]
@MalcolmBrt tu as vu les progrès que tu as faits depuis le début du projet ?

**Comment by MalcolmBrt** [comment]
Oui c'est vrai
