### ISSUE TITLE
:man_beard:  Définir le "LEAD DEV" :sunglasses: 

### ISSUE THREAD

**Issue by adriens** [adriens/temps-attente-streamlit#12]
# :grey_question: Contexte

Toute équipe a besoin d'un lead dev qui va veiller à la bonne atteinte des objectifs, remonter les soucis, etc...

# :dart: Actions

- [x] Communiquer le compte GH du LEAD DEV
- [x] Documenter dans le README au sein d'une section dédiée

**Comment by adriens** [comment]
A fixer ASAP svp @morgancarre @MalcolmBrt

**Comment by MalcolmBrt** [comment]
Avec @morgancarre nous avons décidé que je serai le lead dev.

**Comment by adriens** [comment]
:ok_hand: donc @MalcolmBrt est le lead dev: je documente ça :zap:

**Comment by adriens** [comment]
@MalcolmBrt , tu peux cocher afin de suivre efficacement létat d'avancement stp : 
![image](https://github.com/user-attachments/assets/3b76ca78-ed79-4156-aab4-bb2156ce314f)

**Comment by adriens** [comment]
- https://github.com/adriens/temps-attente-streamlit/pull/13#issuecomment-2362437708

**Comment by adriens** [comment]
Y'a plus qu'à :star_struck:

**Comment by adriens** [comment]
:clap:
