### ISSUE TITLE
:loudspeaker: Créer un social preview

### ISSUE THREAD

**Issue by adriens** [adriens/temps-attente-streamlit#14]
# :grey_question: Contexte

Créer une image lanscape afin que je puisse la charger sur le social preview de la repo.

Vous pouvez utiliser de l'ia générative pour faire ça, https://ideogram.ai/ est bien cool pour ça.

- Faire figurer les logo de l'UNC
- Logo de l'opt
- Faire suggérer des files d'attentes, des charts dataviz, ce que vous pensez qui permet de comprendre en un seul coup d'oeil ce que fait cette repo

# :dart: Actions

- [x] Livrer une image au format paysage dans cette issue
- [x] Configruer la repo pour qu'elle utilise cette image : @adriens 
- [x] Dropper les previews de la repo depuis linkedIn
- [ ] Dropper les previews de la repo depuis Twitter

**Comment by adriens** [comment]
@MalcolmBrt , je te laisse assigner l'issue pour la création de l'image

**Comment by morgancarre** [comment]
Voila une image pour la social preview.
Est-ce qu'elle convient ?
![social preview](https://github.com/user-attachments/assets/88fde3fc-70ef-4d47-b713-9f195e4e0bba)

**Comment by adriens** [comment]
Moi elle me plaît :+1: 
Et à toi @MalcolmBrt ?

**Comment by adriens** [comment]
:thinking: ptet rajouter le logo streamlit ?

**Comment by morgancarre** [comment]
J'ai rajouté le logo de StreamLit sur l'écran 😁: 

![Social Preview_V2](https://github.com/user-attachments/assets/605b8a1f-8344-46f4-b093-86d3ef775b16)

**Comment by MalcolmBrt** [comment]
C'est bon pour moi

**Comment by adriens** [comment]
Social cover uploadée, mais faut attendre un peu pur les preview clean.
:point_right: Je prends la suite

**Comment by adriens** [comment]
Voila ce que ça donne via https://socialsharepreview.com

![image](https://github.com/user-attachments/assets/f58bd85e-bbc2-4310-ad7d-7dfb89b66b1d)

![image](https://github.com/user-attachments/assets/28c9e3e3-76a9-44ae-b777-44780e87f6af)

![image](https://github.com/user-attachments/assets/01f3b56a-f282-4a92-afa5-b561b28c299d)
