### ISSUE TITLE
Choisir une agence dans une liste déroulante

### ISSUE THREAD

**Issue by MalcolmBrt** [adriens/temps-attente-streamlit#21]
- [x] Liste déroulante des agences
- [x] Pouvoir selectionner une agence

**Comment by adriens** [comment]
labels et assigner l'issue 🙏 
![image](https://github.com/user-attachments/assets/f3518de7-f1a3-4485-8024-d76dfa30ff5d)

**Comment by adriens** [comment]
... et milestone of course 😅

**Comment by adriens** [comment]
Je reboot l'app :long_drum:  sur sreamlit...

**Comment by adriens** [comment]
https://opt-nc-temps-attente.streamlit.app/

![image](https://github.com/user-attachments/assets/8f5e1942-57ff-419f-a33f-ba8834c351c7)


@MalcolmBrt , faudra mettre à jour l'url avec l'idAGence en queryParameter... mais là, je pense que ça va aller vite, vous avez fait le plus dur :clap:
