### ISSUE TITLE
Afficher le temps d'attente actuel de l'agence en mode texte

### ISSUE THREAD

**Issue by MalcolmBrt** [adriens/temps-attente-streamlit#22]
- [x] Afficher simplement le temps d'attente à instant t
- [x] Ce temps doit s'auto-refresh

**Comment by adriens** [comment]
Bien positionner les labels et t'assigner sur l'issue 🙏 
![image](https://github.com/user-attachments/assets/6ea4de2f-2fc3-4f58-a32c-8553ceadf0e5)

**Comment by MalcolmBrt** [comment]
@adriens Le temps d'attente a un instant t correspond au realMaxWaitingTimeMs ?
![image](https://github.com/user-attachments/assets/46dfab03-316e-41d8-9b15-e8fa4f696eaf)

**Comment by adriens** [comment]
> Le temps d'attente a un instant t correspond au realMaxWaitingTimeMs ?

Yep :+1:

**Comment by MalcolmBrt** [comment]
Le temps n'a pas vraiment l'air de bouger, la si je refais une requête sur la même agence il est toujours de 390000 ms et on avait déjà la même valeur la semaine dernière en testant donc c'est étrange.
![image](https://github.com/user-attachments/assets/201ee4b7-fbe6-4327-8b59-fb69d846f6df)
On a vérifié sur une autre agence à boulouparis mais c'est pareil, le temps est de 705000 ms et n'a pas l'air d'évoluer.
![image](https://github.com/user-attachments/assets/75641630-3947-4be8-9d48-f47d34d3d5cc)

**Comment by adriens** [comment]
> Le temps n'a pas vraiment l'air de bouger,

Là c le we donc c normal que ça bouge pas... par contre le nombre...c'est pas normal je vais regarder ça de mon côté, y'a ptet un souci côté data/API donc.

Au final, le temps que vous avez côté API doit être le même que celui-ci sur le [site](https://www.opt.nc/service/l-opt-pres-de-chez-moi-trouver-une-agence) : 


![image](https://github.com/user-attachments/assets/2d43ab08-b8cf-411f-b11d-4ebf055617cc)


Dans tous les cas, c'est à peu près le même code que sur https://github.com/opt-nc/generative-art-temps-attente : 

https://github.com/opt-nc/generative-art-temps-attente/blob/main/jumpers/js/sketch.js

cf [code ci-dessous](https://github.com/opt-nc/generative-art-temps-attente/blob/52ad0d138e6dfd82a135b12d85ee3993f71b31c2/jumpers/js/sketch.js#L45C1-L62C2) : 

```js
function draw(){
    clear();
    
    image(bg, 0, 0); // Show background picture
    translate(0, height/2); // Center the origin (0,0) in the middle left side of the screen

    showDate();
    showLogo();

    showTip();

    // Update jumpers
    for(var i = 0; i < jumpers.length; i++){
        jumpers[i].show(jumpers[i].fixedSize/2+i*width/jumpers.length, width/jumpers.length, data[i].realMaxWaitingTimeMs);
        jumpers[i].update();
        jumpers[i].jump(data[i].realMaxWaitingTimeMs);
    }
}
```

:point_right: Partez du principe que c'est bien ce champ et si la valeur de l'API ne matche pas celle du [site](https://www.opt.nc/service/l-opt-pres-de-chez-moi-trouver-une-agence), alors faites-vous un ticket de type bug, je regarderai ça en interne.

**Comment by adriens** [comment]
:information_source: Agence centrale, le samedi 05 Oct 2024 : ` 00:14` : 

![image](https://github.com/user-attachments/assets/8c8b260b-88f4-4103-8519-a8e931571350)

@MalcolmBrt tu as ça aussi via API ?

**Comment by MalcolmBrt** [comment]
Pas vraiment, sur le site de l'opt c'est 14 minutes mais sur l'api j'obtiens 1646000 ms soit ~27 minutes
![image](https://github.com/user-attachments/assets/62acfdd5-8e61-4c7b-9b61-acfcd4425752)

**Comment by adriens** [comment]
OK @MalcolmBrt , je crois que tu as trouvé un incident : tu peux me faire une issue dédiée stp ? et me l'assigner où tu détailles ce qui cloche, comme tu viens lde le faire, avec l'appel http, le screenshot du wite web et en lien ton commentaire https://github.com/adriens/temps-attente-streamlit/issues/22#issuecomment-2394924778 ? 

**:point_right: C'est du super boulot, merci :pray:**

**Comment by adriens** [comment]
:information_source: En attendant, fais comme si la donnée était juste, c'est pas grave, nous ,on continue à développer l'application

**Comment by MalcolmBrt** [comment]
D'accord pas de soucis, j'ai crée l'issue :
- #31

**Comment by adriens** [comment]
C'est parfait, elle top cette collab :clap:

**Comment by adriens** [comment]
:information_source:  Mon équipe s'y colle lundi
