### ISSUE TITLE
Un dataviz simple mais efficace indiquant si l'agence est en mode Vert/Jaune/rouge selon la fourchette du temps d'attente

### ISSUE THREAD

**Issue by MalcolmBrt** [adriens/temps-attente-streamlit#23]
- [ ] Diagramme Gauge
Dans ce style :
![image](https://github.com/user-attachments/assets/1cc9687d-7fce-4e10-afab-51c2dc9fd866)

Ressources :
https://plotly.com/python/gauge-charts/
https://docs.streamlit.io/develop/api-reference/charts/st.plotly_chart/

**Comment by adriens** [comment]
YES 👍

**Comment by adriens** [comment]
Assigner toi sur l'issue et labels svp
![image](https://github.com/user-attachments/assets/05ada8c0-4980-48a3-b432-7c857c0493d3)
