### ISSUE TITLE
Clé API depuis variable d'environnement

### ISSUE THREAD

**Issue by MalcolmBrt** [adriens/temps-attente-streamlit#24]
- [x] Charger la clé depuis une variable d'environnement
- [x] Mettre à jour la documentation

**Comment by adriens** [comment]
@morgancarre tu veux tester la branche ?

**Comment by morgancarre** [comment]
J'ai testé, ça fonctionne bien 👍​

**Comment by adriens** [comment]
> J'ai testé, ça fonctionne bien 👍​

Alors GO pour merge @morgancarre :muscle:
