### ISSUE TITLE
:cinema: Streamlit Features You Always Ask Me About are Coming SOON : 5' video :bulb: 

### ISSUE THREAD

**Issue by adriens** [adriens/temps-attente-streamlit#26]
# :grey_question: A propos

Parties intéressantes : 

- les thèmes
- Déployer sur StreamLit cloud qui pourait nous être utile :thinking: 

# :dart: Action

Regarder [Streamlit Features You Always Ask Me About are Coming SOON](https://www.youtube.com/watch?v=lnvzyw1KCs0) pour inspiration : 

- [x] @morgancarre 
- [x] @MalcolmBrt 
- [x] @adriens

**Comment by adriens** [comment]
:wave:  @morgancarre , on t'attend stp

La nouvelle milestone v1.0 a été lancée mais la précédente n'a pas été terminée : on doit d'abord finir ce qui est entamé : 
![image](https://github.com/user-attachments/assets/89407837-cb15-467c-9c5a-9d90a7dce5ef)

**Comment by morgancarre** [comment]
C'est good pour moi

**Comment by adriens** [comment]
> C'est good pour moi

Alors tu peux fermer l'issue

**Comment by adriens** [comment]
👍
