### ISSUE TITLE
:bug: Préciser la timezone dans l'app

### ISSUE THREAD

**Issue by adriens** [adriens/temps-attente-streamlit#28]
# :grey_question: Contexte

Cf : 
- https://github.com/adriens/temps-attente-streamlit/issues/27#issuecomment-2380323777

La TZ utilisée depuis le web est celle du client, or nous... on veut que ce soit fixé à la NCL, pas sur la TZ du visiteur

# :dart: Action

- Forcer la TZ sur `Pacific/Noumea`

# :ok: DoD

Sur https://opt-nc-temps-attente.streamlit.app/ : voir afficher la date courante en NCL

# :bulb: Tips

Paquet pip : 

```
pip install pytz
```

```python
import streamlit as st
from datetime import datetime
import pytz

# Fixer le fuseau horaire de la Nouvelle-Calédonie
ncl_tz = pytz.timezone('Pacific/Noumea')

# Obtenir l'heure actuelle dans ce fuseau horaire
ncl_time = datetime.now(ncl_tz)

# Afficher l'heure locale dans l'application Streamlit
st.write("Heure actuelle en Nouvelle-Calédonie :", ncl_time.strftime("%Y-%m-%d %H:%M:%S"))
```

**Comment by MalcolmBrt** [comment]
En effet, j'avais fait en sorte de simplement modifier le fuseau horaire du conteneur docker via le dockerfile
```dockerfile
ENV TZ=Pacific/Noumea
``` 
Mais comme la version déployé dépend directement du dépôt et non du dockerfile, ça n'a pas prit en compte le bon fuseau.
Je vais modifier ça directement en Python donc.

**Comment by adriens** [comment]
> En effet, j'avais fait en sorte de simplement modifier le fuseau horaire du conteneur docker via le dockerfile

Yes, c top pour ceux qui vont déloyer via l'image donc faut le garder. Là, avec Streamlit CLoud, c'est eux qui vont carrément builder l'app depuis le python, donc faut les deux :+1: 

> 
> Mais comme la version déployé dépend directement du dépôt et non du dockerfile, ça n'a pas prit en compte le bon fuseau.
> Je vais modifier ça directement en Python donc.

Yes, je pense que c'est clean de positionner aux deux endroits :+1:

**Comment by adriens** [comment]
@MalcolmBrt  : j'ai rebooté l'app et le fix est bien déployé :clap: 

https://opt-nc-temps-attente.streamlit.app/

![image](https://github.com/user-attachments/assets/e9471ba1-ee63-41ad-9f37-7935ee00c914)
