### ISSUE TITLE
:bug:  Temps d'attente API ne se mettant pas à jour

### ISSUE THREAD

**Issue by MalcolmBrt** [adriens/temps-attente-streamlit#31]
Le temps d'attente des agences n'est pas à jour par rapport au temps observé sur [le site de l'OPT](https://www.opt.nc/service/l-opt-pres-de-chez-moi-trouver-une-agence)
Ici le site indique 14 minutes pour l'agence principale :
![image](https://github.com/user-attachments/assets/4656fd86-8b01-4218-adc6-e6727c171574)
Mais l'API indique 1646000 ms soit ~27 minutes :
![image](https://github.com/user-attachments/assets/b75a4e7c-a04b-465e-a4d7-c4fa04785bd1)
Le problème semble être le même pour plusieurs agences (voir https://github.com/adriens/temps-attente-streamlit/issues/22#issuecomment-2394924778)

**Comment by adriens** [comment]
J'ai créé une issue interne pour mon équipe, on s'y colle lundi :rocket:

**Comment by adriens** [comment]
:pause_button:

**Comment by mbarre** [comment]
Hello,

Il semblerait qu'on retourne pas au niveau de l'api, le champ utilisé sur le site des agences.

![image](https://github.com/user-attachments/assets/e69d95c4-a3f0-4fb0-8eee-1407782687f2)

**Comment by adriens** [comment]
OK, super, @mbarre , tu peux nous donner un aperçu des champs que l'on va ajouter stp ?

**Comment by adriens** [comment]
@MalcolmBrt , on va traviiler tout ça en backoffice et on vous livrera une API plus riche : vous allez avoir davantage de champs :gift:

**Comment by adriens** [comment]
En attente feedbacks @mbarre pour la suite des actions
:pause_button:

**Comment by mbarre** [comment]
J'ai préparé le correctif, je déploie demain.

**Comment by adriens** [comment]
> J'ai préparé le correctif, je déploie demain.

T'es au top @mbarre ... avec enrichissement apigee?

**Comment by mbarre** [comment]
@MalcolmBrt @morgancarre 

C'est bon, c'est fait :+1: 

```json
{
  "idAgence": 4314,
  "designation": "Agence de NOUMEA AGENCE PRINCIPALE",
  "realMaxWaitingTimeMs": 0,
  "realAvgWaitingTimeMs": 0,
  "estimatedAvgWaitingTimeMs": 0,
  "coordonneeX": 445672.8500000015,
  "coordonneeY": 214091.58000000007,
  "coordonneeXPrecise": 445670,
  "coordonneeYPrecise": 214089,
  "position": {
    "lat": -22.275318886068586,
    "lon": 166.4431673905479
  },
  "commune": "NOUMEA",
  "type": "AGENCE",
  "codeESirius": "site1",
  "codePostal": "98841",
  "lieuDitOuTribu": "",
  "localite": "NOUMEA CEDEX",
  "idRefloc": "05ADNC0118049900070000",
  "codePostalRefloc": "98800",
  "localiteRefloc": "NOUMEA",
  "updatedDate": "2024-10-09T15:42:07.926"
}
```

**Comment by MalcolmBrt** [comment]
Okay merci

**Comment by adriens** [comment]
Bravo @mbarre et @MalcolmBrt  : vous avez fait un super boulot d'équipe, ça fait progresser l'API :clap: :pray:
