### ISSUE TITLE
🔁 Optimisation et refactorisation des appels API

### ISSUE THREAD

**Issue by MalcolmBrt** [adriens/temps-attente-streamlit#37]
- [x] Créer une constante `INTERVALLE_AUTOREFRESH` pour définir le délai de rafraîchissement des données
- [x] Refactoriser la logique de récupération des communes en une fonction `fetch_communes()` dans utils.py
- [x] Refactoriser la logique de récupération des données d'une agence en une fonction `fetch_agences(commune)` dans utils.py
- [x] Utiliser `@st.cache_data()` pour mettre en cache les données avec un TTL de `INTERVALLE_AUTOREFRESH`

Rssources : 
[Documentation Streamlit - Mise en cache](https://docs.streamlit.io/develop/api-reference/caching-and-state/st.cache_data)

**Comment by adriens** [comment]
> Créer une constante INTERVALLE_AUTOREFRESH pour définir le délai de rafraîchissement des données

Yes, pas moins de 2' : donc 3' serait très bien

**Comment by adriens** [comment]
> Refactoriser la logique de récupération des communes en une fonction fetch_communes() dans utils.py

Yes, et bien veiller à ne l'appeler qu'une seule fois afin d'éviter les appels API inutiles (imagine que ces dernies sont payants... ou que tu fonctionnes sur une batterue et que donc les ressources sont limités...)

**Comment by adriens** [comment]
> Utiliser @st.cache_data() pour mettre en cache les données avec un TTL de INTERVALLE_AUTOREFRESH

:star_struck: très joli ça @MalcolmBrt [`st.cache_data`](https://docs.streamlit.io/develop/api-reference/caching-and-state/st.cache_data) :clap:
