### ISSUE TITLE
📊 Ajouter l'historique des temps d'attente pour chaque agence

### ISSUE THREAD

**Issue by MalcolmBrt** [adriens/temps-attente-streamlit#38]
- [x] Récupérer l'historique sur l'endpoint `/agences/{id}/historique`
- [x] Implémenter l'affichage des données sous forme de courbe/barres
- [x] Mettre à jour le graphique à intervalles réguliers

Ressources :
[Documentation Streamlit - Affichage de graphiques](https://docs.streamlit.io/develop/api-reference/charts)

**Comment by adriens** [comment]
@MalcolmBrt , sur chaque issuePR, il faut positionner le label `BULD` ou `RUN` : je te fais une issue dédiée afin que tu comprennes à quoi ça sert :zap:

**Comment by adriens** [comment]
:point_down: 
- https://github.com/adriens/temps-attente-streamlit/issues/39

**Comment by MalcolmBrt** [comment]
Ah oui je me demandais justement ce que ça signifiait, merci.

**Comment by adriens** [comment]
> Ah oui je me demandais justement ce que ça signifiait, merci.

Yep, je me suis rappelé que ce matin que j'avais produit un article dédié à ce concept :sweat_smile:

**Comment by adriens** [comment]
hello @MalcolmBrt , as-tu fait des avancées sur cette feature ?

**Comment by MalcolmBrt** [comment]
Euh non pas vraiment puisque je l'ai assignée a Morgan

**Comment by adriens** [comment]
> Euh non pas vraiment puisque je l'ai assignée a Morgan

Yes, du coup, quelles sont les news @morgancarre ?

**Comment by morgancarre** [comment]
Salut pardon pour l'inactivité. Oui j'ai avancé sur la logique mais l'end point de l'historique à un bug je pense je n'arrête pas d'avoir une erreur .

j'ai fait une issue #50 .

**Comment by adriens** [comment]
En attente du fix de : 
- #50 

par @Supervinh 
:pause_button:
