### ISSUE TITLE
:student: Le `BULD` et le `RUN` : kézako ?

### ISSUE THREAD

**Issue by adriens** [adriens/temps-attente-streamlit#39]
# :grey_question: Contexte

En entreprise, une façon de diviser les activités est de les classer en `BUILD` vs. `RUN` où  : 

- `BUILD` : activités de création de valeur nouvelle : nouvelle feature, etc...
- `RUN` : tout ce qui doit être fait pour que le système puisse fonctionner... **mais qui ne crée pas de valeur pour le client final**

Pour cela il esiste deux labels à positionner sur les issues et PR : 

![image](https://github.com/user-attachments/assets/4ee897f5-505f-4cf6-a7be-6f8460a46c5e)

![image](https://github.com/user-attachments/assets/03265856-161d-4521-a3a6-b418f2f0ec18)

**:point_right: Le but de cette issue est de vous permettre de comprendre les principes de cette catégorisation et ce que cela permet en termes de pilotage.**, cf commentaire : 

- https://github.com/adriens/temps-attente-streamlit/issues/38#issuecomment-2408184709

# :dart: Actions

- [x] @MalcolmBrt : Lire et regarder video de   [⚖️ Sankey Diagram : how much do you juggle with BUILD & RUN (GitHub issues API) 🎫](https://dev.to/optnc/sankey-diagram-how-much-do-you-juggle-with-build-run-github-issues-api-2lgh)
- [x] @morgancarre  : Lire et regarder video de   [⚖️ Sankey Diagram : how much do you juggle with BUILD & RUN (GitHub issues API) 🎫](https://dev.to/optnc/sankey-diagram-how-much-do-you-juggle-with-build-run-github-issues-api-2lgh)
- [x] Veiller  ce que chaque issue/PR aie ses labels posés

![image](https://github.com/user-attachments/assets/f3cd3a07-70a5-48e6-9724-9868ddaaa683)

**Comment by adriens** [comment]
@morgancarre @MalcolmBrt svp c'est un quickfix pouvez-vous vous occupper de cette issue ?

**Comment by adriens** [comment]
Status : 
![image](https://github.com/user-attachments/assets/94ce5273-d7f1-453b-a03b-c15e2e9e6784)

**Comment by MalcolmBrt** [comment]
Je vérifie également pour les issues/pr fermées ?

**Comment by adriens** [comment]
> Je vérifie également pour les issues/pr fermées ?

Yes, ça serait cool, tu peux faire ça en masse avec la vue en liste : tu peux éduter le label en masse tu verrras.

Après, à voir si on attend @morgancarre :thinking: Je te laisse voir avec lui

**Comment by morgancarre** [comment]
C'est bon on s'est occupé de positionner les labels "BUILD" et "RUN" sur toutes les issues :)

**Comment by adriens** [comment]
Alors vous pouvez fermer
