### ISSUE TITLE
:information_source:  Profils GH clean et informatifs

### ISSUE THREAD

**Issue by adriens** [adriens/temps-attente-streamlit#4]
# :grey_question: A propos

Les profils GH sont actuellement pauvres pour : 

- https://github.com/MalcolmBrt
- https://github.com/morgancarre

On ne sait pas exacteent avec qui on collabore

![image](https://github.com/user-attachments/assets/20c8b28e-88b1-463f-9cf1-78c674add71b)
![image](https://github.com/user-attachments/assets/494223cf-38b7-412a-9862-5cc690a92fda)

Exemple du le mien : 

![image](https://github.com/user-attachments/assets/3f652237-19d9-4004-8598-623a6929ea68)

# :bookmark: Ressources

- [Managing your profile README](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/customizing-your-profile/managing-your-profile-readme)
- https://github.com/abhisheknaiidu/awesome-github-profile-readme
- [GitHub Profile README Generator](https://rahuldkjain.github.io/gh-profile-readme-generator/)
[Star this repo21174](https://github.com/rahuldkjain/github-profile-readme-generator)

# :dart: Actions

- [x] Rendre activité publique  de @MalcolmBrt's publique et non pas _"@MalcolmBrt's activity is private"_
- [x] Page linkedIn pour Malcolm
- [x] Page linkedIn pour Malcolm Morgan
- [x] Page de profil renseignée pour https://github.com/MalcolmBrt
- [x] Page de profil renseignée pour https://github.com/morgancarre

# :ok: DoD

Dropper les screenshots de vos profils modifiés

**Comment by adriens** [comment]
A vous de jouer @morgancarre @MalcolmBrt :pray: 
Pensez à vous mettre des avatars aussi sur GH svp

**Comment by MalcolmBrt** [comment]
Bonjour, nous avons enrichi nos profils. Voici le miens : 
![image](https://github.com/user-attachments/assets/5ca9938c-5a78-4cec-80da-14d78ac9dac0)

**Comment by adriens** [comment]
Super cool @MalcolmBrt :pray:

**Comment by adriens** [comment]
Page linkedIn pas good quand je clique sur ton porfil GH, l'url est pas bonne @MalcolmBrt : 

https://www.linkedin.com/in/https:/www.linkedin.com/in/malcolm-bertaina/

![image](https://github.com/user-attachments/assets/b2ba4a31-5e6e-42ca-a9d2-cbf1ec749398)

**Comment by adriens** [comment]
:point_right:  Il manque le linkedIn de @morgancarre

**Comment by MalcolmBrt** [comment]
J'ai corrigé pour ma part

**Comment by adriens** [comment]
> J'ai corrigé pour ma part

Yes, je viens de tester c'est :ok_man: 

https://www.linkedin.com/in/malcolm-bertaina/

![image](https://github.com/user-attachments/assets/4a3a0715-a66e-401b-a2a0-b5dc614af916)

@MalcolmBrt , je te laisse driver @morgancarre pour qu'il fixe sa partie. EN tant que lead dev (cf #12 ), c'est à toi que revient la mission de veiller à ce que tout déroule fluide :pray:

**Comment by morgancarre** [comment]
C'est bon pour mon profil Github et mon profil LinkeDin (le lien marche sur mon profil 😉)

![Capture d'écran 2024-09-21 164627](https://github.com/user-attachments/assets/210c889a-bff2-4cdf-aec1-c72835890e12)

**Comment by adriens** [comment]
Je teste ça :zap: @morgancarre

**Comment by adriens** [comment]
https://www.linkedin.com/in/morgan-carr%C3%A9-7a948232a/

![image](https://github.com/user-attachments/assets/db85ea6c-19dd-46e8-b1b5-a8fc1c365a2c)
![image](https://github.com/user-attachments/assets/627695a6-20cc-4888-b632-91d73ea3d5cc)


:clap:
