### ISSUE TITLE
🔗 Ajouter l'id de l'agence sélectionnée en paramètre d'URL

### ISSUE THREAD

**Issue by MalcolmBrt** [adriens/temps-attente-streamlit#40]
# 📝 Tâches
- [x] Mettre à jour l'URL après sélection d'une agence
- [x] Récupérer les paramètres d'URL lors du chargement
- [x] Adapter le menu déroulant pour gérer la présélection basée sur l'ID dans l'URL

# 🛠️ Ressources

- [Documentation Streamlit - Paramètres d'URL](https://docs.streamlit.io/develop/api-reference/caching-and-state/st.query_params)
- [Documentation Streamlit - Menu déroulant](https://docs.streamlit.io/develop/api-reference/widgets/st.selectbox)

**Comment by adriens** [comment]
:clap: @MalcolmBrt :point_down: 
![image](https://github.com/user-attachments/assets/f844ae88-1e0e-4635-a73e-f44477b8dc7b)

:bulb: C'est pour quand un ticket est super bien rédigé
