### ISSUE TITLE
Menu gauche rértactable

### ISSUE THREAD

**Issue by adriens** [adriens/temps-attente-streamlit#44]
# :grey_question: A propos

Actuellement, le menu de gauche permettant de choisir une commune/agence est toujours là alors que : 

- parfois on vuet juste choisir une agence
- on veut afficher sur une TV en permaence une unique agence et donc avoir un affichage clean et simple

![image](https://github.com/user-attachments/assets/7587c75b-8daa-4423-90b1-7fc2898a6329)

# :bulb: Idée

Rendre le menu de gauche rétractable afin que l'on ne voit plus que l'affichage principal

**Comment by MalcolmBrt** [comment]
Il l'est déjà de base normalement, il faut survoler la barre :
![image](https://github.com/user-attachments/assets/54b26bbc-b881-4a2c-8451-a93c9a0c3551)

**Comment by adriens** [comment]
En effet :sweat_smile: 
![image](https://github.com/user-attachments/assets/3aa396ee-4bf5-404b-bfcf-aee06339c822)

**Comment by adriens** [comment]
:thinking: moyen de mettre un tooltip sur le collapser ?

**Comment by MalcolmBrt** [comment]
C'est a dire ? J'ai pas bien compris

**Comment by adriens** [comment]
Quand la souris passe au-dessus du widget qui permet de replier, metre un tooltp qui dit que ça "collapse" le menu ou inversement "montre" le menu.
