### ISSUE TITLE
:bar_chart: Un front-end autorefresh avec historique :repeat: 

### ISSUE THREAD

**Issue by adriens** [adriens/temps-attente-streamlit#5]
# :dart: DoD

- [x] Builder en local l'image Docker
- [x] Démarrer l'application en local sur une Ubuntu
- [x] Choisir une agence
- [x] Constater un widget qui affiche le temps d'attente instantané et qui se rafraîchit automatiquement toutes les 2'
- [x] Afficher via un dataviz (courbe, barplot,...) l'hisorique des temps d'attente de la journée pour cette agence
- [x] Dropper les screenshots ici

**Comment by adriens** [comment]
@morgancarre @MalcolmBrt  : pour le refresh : [Streamlit Autorefresh](https://discuss.streamlit.io/t/streamlit-autorefresh/14519) :raised_hands: 


```python
import streamlit as st
from streamlit_autorefresh import st_autorefresh

# update every 5 mins
st_autorefresh(interval=5 * 60 * 1000, key="dataframerefresh")

def get_data():
    # Perform some request to get a dataframe
    client.get()
    return df

st.dataframe(get_data())
```

**Comment by MalcolmBrt** [comment]
Il faut ajouter le dataviz pour l'historique mais est qu'on doit garder le diagramme gauge avec ?

**Comment by adriens** [comment]
> Il faut ajouter le dataviz pour l'historique mais est qu'on doit garder le diagramme gauge avec ?

dans un premier temps, chargeons les deux et en les voyant, on pourra ptet trancher plus facilement en faveur de l'un u l'autre... ou avoir un menu qui permet de ne voir que l'un ou l'autre.

:point_right: Oublie pas de permettre de choper l'agence qu'on veut en passant l' `idAgence` dans l'url, comme ça c supe rpartique pour partager le tdb d'une agence donnée avec un QrCode par exemple : ptet faire une issue dédiée pour ça non ?

**Comment by MalcolmBrt** [comment]
> 👉 Oublie pas de permettre de choper l'agence qu'on veut en passant l' `idAgence` dans l'url, comme ça c supe rpartique pour partager le tdb d'une agence donnée avec un QrCode par exemple : ptet faire une issue dédiée pour ça non ?

Ah oui j'avais oublié ce détail, je vais en créer une issue dédié

**Comment by adriens** [comment]
je pense que c'est un quickfix (ie. super facile à coder), mais c'est toi qui code et donc es le plus en mesure de produire cette analyse.
Si c'est un quickfix, alors on devra le prioriser afin de le délivrer avant les autres issues plus complexes afin d'optimiser le flux de création de valeur de notre produit :thought_balloon:

**Comment by MalcolmBrt** [comment]
D'accord mais je préfère terminé l'issue 
- #37 

Puisque je bouge pas mal de code dans utils.py, je pense que ce sera plus simple de le faire après

**Comment by adriens** [comment]
> Puisque je bouge pas mal de code dans utils.py, je pense que ce sera plus simple de le faire après

Très bonne approche :+1:

**Comment by adriens** [comment]
> D'accord mais je préfère terminé l'issue

Excellent réflexe :clap: :pray:

**Comment by MalcolmBrt** [comment]
> * Builder en local l'image Docker

![image](https://github.com/user-attachments/assets/e3fd31ef-3a69-414c-904a-5ac3d84bc239)

> * Démarrer l'application en local sur une Ubuntu

![image](https://github.com/user-attachments/assets/996ad430-3f11-4113-bb76-61b3aa5d77ba)

> * Choisir une agence

![image](https://github.com/user-attachments/assets/443ab108-ea8a-4874-b0ca-bd5ad5e9c6ab)

> * Constater un widget qui affiche le temps d'attente instantané et qui se rafraîchit automatiquement toutes les 2'

![image](https://github.com/user-attachments/assets/8dc77b99-7db7-46f9-a659-a114d66d4c2a)

> * Afficher via un dataviz (courbe, barplot,...) l'hisorique des temps d'attente de la journée pour cette agence

![image](https://github.com/user-attachments/assets/cc55e229-c147-47f2-80ea-dfeb1c841dcb)

**Comment by adriens** [comment]
Super intéressant de voir monter le temps comme ça. Hâte de voir ce qui se passe au moment de la pause déjeuner également...
