### ISSUE TITLE
:rotating_light: Problème API - Endpoint historique 

### ISSUE THREAD

**Issue by morgancarre** [adriens/temps-attente-streamlit#50]
Bonjour @adriens, 
J'ai un problème avec l'API sur l'endpoint : `https://api.opt.nc/temps-attente-agences/agences/{id}/historique`

J'ai essayé plusieurs fois de faire la reqûete pour récupérer l'historique  mais j'ai toujours une erreur : 

400 OK 
```json
{
  "fault": {
    "faultstring": "OASValidation OAS-Validation with resource \"oas://spec.yaml\": failed with reason: \"[ERROR - String '2024-08-10T12:15:50' is invalid against requested date format(s) [yyyy-MM-dd'T'HH:mm:ssZ, yyyy-MM-dd'T'HH:mm:ss.[0-9]{1,12}Z]: [], ERROR - String '2024-08-10T15:15:50' is invalid against requested date format(s) [yyyy-MM-dd'T'HH:mm:ssZ, yyyy-MM-dd'T'HH:mm:ss.[0-9]{1,12}Z]: []]\"",
    "detail": {
      "errorcode": "steps.oasvalidation.Failed"
    }
  }
}
```

pourtant je rentre bien les bons paramètres  :

```bash
http --session=session.json GET https://api.opt.nc/temps-attente-agences/agences/1151/historique debut=="2024-08-10T12:15:50" fin=="2024-08-10T15:15:50"
```

Ce bug bloque l'issue #38 : **[Ajouter l'historique des temps d'attente pour chaque agence](https://github.com/opt-nc/opt-tempo/issues/38)**.
@MalcolmBrt à testé aussi et il a le même problème.

Cela vient-il de nous où l'API est buggée sur cet endpoint ?

**Comment by adriens** [comment]
Je vais regarder ça avec @mbarre mais y'a des  chances que ce soit chez nous

**Comment by morgancarre** [comment]
Ok ça marche

**Comment by adriens** [comment]
Tu peux mettre la requête httpie pour reproduire stp ?
On attaquera cette issue en interne demain matin

**Comment by morgancarre** [comment]
ok pas de souci : 
http --session=session.json GET https://api.opt.nc/temps-attente-agences/agences/1151/historique debut=="2024-08-10T12:15:50" fin=="2024-08-10T15:15:50"

**Comment by adriens** [comment]
Top les gars merci pour tous ces feedbacks c du bon boulot

**Comment by adriens** [comment]
@morgancarre , tu peux rendre ton issue un peu mieux rédigée avec la partie json valid et correctement citée stp : 
![image](https://github.com/user-attachments/assets/0f0afafc-1152-4a95-afe9-33779b369dc7)

:point_down: 

```json
{
  "fault": {
    "faultstring": "OASValidation OAS-Validation with resource \"oas://spec.yaml\": failed with reason: \"[ERROR - String '2024-08-10T12:15:50' is invalid against requested date format(s) [yyyy-MM-dd'T'HH:mm:ssZ, yyyy-MM-dd'T'HH:mm:ss.[0-9]{1,12}Z]: [], ERROR - String '2024-08-10T15:15:50' is invalid against requested date format(s) [yyyy-MM-dd'T'HH:mm:ssZ, yyyy-MM-dd'T'HH:mm:ss.[0-9]{1,12}Z]: []]\"",
    "detail": {
      "errorcode": "steps.oasvalidation.Failed"
    }
  }
}
```

**Comment by adriens** [comment]
... et dans le contexte préciser quelle issue cela bloque stp

**Comment by adriens** [comment]
Ticket interne en cours de rédaction...

**Comment by adriens** [comment]
Ticket dans le pipe interne et prise en main par @Supervinh :clap:

**Comment by adriens** [comment]
:point_right: Prochaine étape : on attend un update de @Supervinh qui va commencer par reproduire l'issue
:pause_button:

**Comment by Supervinh** [comment]
Hello, j'ai bien réussi à reproduire le problème sur APIGEE (code erreur 400), je regarde comment le résoudre

**Comment by adriens** [comment]
> Hello, j'ai bien réussi à reproduire le problème sur APIGEE (code erreur 400), je regarde comment le résoudre


Top
Merci @Supervinh et bienvenue sur ce projet

**Comment by morgancarre** [comment]
> @morgancarre , tu peux rendre ton issue un peu mieux rédigée avec la partie json valid et correctement citée stp : ![image](https://private-user-images.githubusercontent.com/5235127/378591293-0f0afafc-1152-4a95-afe9-33779b369dc7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1NTM1NDMsIm5iZiI6MTcyOTU1MzI0MywicGF0aCI6Ii81MjM1MTI3LzM3ODU5MTI5My0wZjBhZmFmYy0xMTUyLTRhOTUtYWZlOS0zMzc3OWIzNjlkYzcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjFUMjMyNzIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmUxZThkMWJiZWRlYzY4NDhjYWFlZjI2MWRhNjE5NGYwNTMzZjA3Njc2OGFiYmU1MDM4MzA1N2I4ZmM3ZmVjMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.mprHnj4K3VB1ivOzBLEx1Z5OgkCkflY2hRTOXKnE64o)
> 
> 👇
> 
> ```json
> {
>   "fault": {
>     "faultstring": "OASValidation OAS-Validation with resource \"oas://spec.yaml\": failed with reason: \"[ERROR - String '2024-08-10T12:15:50' is invalid against requested date format(s) [yyyy-MM-dd'T'HH:mm:ssZ, yyyy-MM-dd'T'HH:mm:ss.[0-9]{1,12}Z]: [], ERROR - String '2024-08-10T15:15:50' is invalid against requested date format(s) [yyyy-MM-dd'T'HH:mm:ssZ, yyyy-MM-dd'T'HH:mm:ss.[0-9]{1,12}Z]: []]\"",
>     "detail": {
>       "errorcode": "steps.oasvalidation.Failed"
>     }
>   }
> }
> ```

C'est good j'ai modifié

**Comment by adriens** [comment]
Top, merci @morgancarre :pray:

**Comment by Supervinh** [comment]
@morgancarre @MalcolmBrt Pour vous tenir au courant, j'ai en effet la même erreur 400 en passant par APIGEE (testé sur navigateur et en console de commande). Mais, en le testant sur [Killercoda](https://killercoda.com/opt-labs/course/opt-temps-attente-agences) et sur [Rapidapi](https://rapidapi.com/opt-nc-opt-nc-default/api/temps-attente-en-agence/playground/apiendpoint_a4657945-b05c-43b8-9e90-0df6ae36b139) tout est fonctionnel (je vous laisse tester si vous le voulez, cela peut servir comme solution de secours pour l'instant).
Actuellement la seule requête fonctionnelle en passant par APIGEE est si vous ne passez aucune date de début ni de fin, ce qui vous retourne tous les résultats possibles.
```shell
http GET https://api.opt.nc/temps-attente-agences/agences/1151/historique x-apikey:"key" 
```

Le ticket a été remonté en interne et on vous tient au courant dès qu'on a plus d'infos

**Comment by adriens** [comment]
Top @Supervinh très bon le service client  .

**Comment by MalcolmBrt** [comment]
Ça fonctionne sur killercoda mais par contre le fuseau horaire est UTC, c'est normal ?

`http get :8080/agences/4165/historique debut==2024-10-22T03:40:00`
```shell
HTTP/1.1 200 OK
Content-Type: application/json;charset=UTF-8
transfer-encoding: chunked

[
    {
        "realMaxWaitingTimeMs": 96000,
        "timestamp": "2024-10-22T03:40:13.696"
    },
    {
        "realMaxWaitingTimeMs": 212000,
        "timestamp": "2024-10-22T03:42:08.839"
    },
    {
        "realMaxWaitingTimeMs": 0,
        "timestamp": "2024-10-22T03:44:08.273"
    }
]
```

**Comment by adriens** [comment]
@MalcolmBrt tu peux nous faire une issue dédiée pour setter la TZ dans le shell sur killercoda stp ? Et dire comment  le faire également 
@Supervinh patchera ça. 
Btw cool que tu y sois allé sur killercoda c fait pour ca @MalcolmBrt

**Comment by MalcolmBrt** [comment]
Ça marche pas quand j'essaie de mettre la tz :
![image](https://github.com/user-attachments/assets/3c0fd2f0-3a04-4048-846f-dbec785eca67)

**Comment by Supervinh** [comment]
> Ça marche pas quand j'essaie de mettre la tz.

@MalcolmBrt Attention, là ta requête n'est plus bonne car tu n'envoies pas un argument valide pour la date de début. Ce que @adriens te demande c'est de modifier la TZ directement dans le shell sur killercoda, ta requête elle ne va pas changer.

**Comment by MalcolmBrt** [comment]
Ah d'accord, je ne l'avais pas compris comme ça

**Comment by adriens** [comment]
Yep ça c de la collaboration 
Lets go

**Comment by MalcolmBrt** [comment]
Alors en changeant la tz du shell ça ne change rien, j'ai plutôt changé celle du container et là ça fonctionne bien.
Si c'est ok, je m'occupe d'en faire l'issue.

**Comment by adriens** [comment]
> j'ai plutôt changé celle du container et là ça fonctionne bien.
Si c'est ok, je m'occupe d'en faire l'issue.

Yes, c'est carrément mieux :clap:

**Comment by morgancarre** [comment]
Bonjour, pour RapidAPI je n'arrive pas à faire fonctionner l'endpoint : 
![image](https://github.com/user-attachments/assets/0e4efc6e-2c7f-4ccc-bf30-ab0cdca335cb)

**Comment by morgancarre** [comment]
Bonjour, pour RapidAPI je n'arrive pas à faire fonctionner l'endpoint :
![image](https://github.com/user-attachments/assets/64f0de0e-75cc-4b65-9ef5-eea2167c5d5d)

**Comment by Supervinh** [comment]
@morgancarre De mon côté tout fonctionne, je pense que tu as simplement oublié d'ajouter ta clé rapidapi à ta requête (n'hésite pas à rajouter des " " autour des valeurs de tes arguments également

<pre><font color="#26A269"><b>➜  </b></font><font color="#2AA1B3"><b>apt.conf.d</b></font> http GET https://temps-attente-en-agence.p.rapidapi.com/agences/4151/historique debut==&quot;2024-10-23T00:00:00&quot; x-rapidapi-host:&quot;temps-attente-en-agence.p.rapidapi.com&quot; x-rapidapi-key:&quot;bf6891fb7cbe0a1eb58955&quot;
<font color="#12488B">HTTP</font>/<font color="#12488B">1.1</font> <font color="#12488B">200</font> <font color="#2AA1B3">OK</font>
<font color="#2AA1B3">Connection</font>: keep-alive
<font color="#2AA1B3">Content-Type</font>: application/json;charset=UTF-8
<font color="#2AA1B3">Date</font>: Thu, 24 Oct 2024 02:32:48 GMT
<font color="#2AA1B3">Server</font>: RapidAPI-1.2.8
<font color="#2AA1B3">Transfer-Encoding</font>: chunked
<font color="#2AA1B3">X-RapidAPI-Region</font>: AWS - ap-southeast-2
<font color="#2AA1B3">X-RapidAPI-Request-Id</font>: d6ce247ad072e2ae95595ee6fa593aac8f69cde4900a350dd8970d37cee317dd
<font color="#2AA1B3">X-RapidAPI-Version</font>: 1.2.8
<font color="#2AA1B3">X-RateLimit-rapid-free-plans-hard-limit-Limit</font>: 500000
<font color="#2AA1B3">X-RateLimit-rapid-free-plans-hard-limit-Remaining</font>: 499968
<font color="#2AA1B3">X-RateLimit-rapid-free-plans-hard-limit-Reset</font>: 2497312
<font color="#2AA1B3">set-cookie</font>: LB_BACKEND_ID=2; path=/
<font color="#2AA1B3">strict-transport-security</font>: max-age=31536000; includeSubdomains; preload
<font color="#2AA1B3">x-content-type-options</font>: nosniff

[
<font color="#D0CFCC">    </font>{
<font color="#D0CFCC">        </font><font color="#2A7BDE">&quot;realMaxWaitingTimeMs&quot;</font>:<font color="#D0CFCC"> </font><font color="#12488B">0</font>,
<font color="#D0CFCC">        </font><font color="#2A7BDE">&quot;timestamp&quot;</font>:<font color="#D0CFCC"> </font><font color="#A2734C">&quot;2024-10-23T00:00:17.779&quot;</font>
<font color="#D0CFCC">    </font>},
<font color="#D0CFCC">    </font>{
<font color="#D0CFCC">        </font><font color="#2A7BDE">&quot;realMaxWaitingTimeMs&quot;</font>:<font color="#D0CFCC"> </font><font color="#12488B">0</font>,
<font color="#D0CFCC">        </font><font color="#2A7BDE">&quot;timestamp&quot;</font>:<font color="#D0CFCC"> </font><font color="#A2734C">&quot;2024-10-23T00:02:09.214&quot;</font>
<font color="#D0CFCC">    </font>},
<font color="#D0CFCC">    </font>{
<font color="#D0CFCC">        </font><font color="#2A7BDE">&quot;realMaxWaitingTimeMs&quot;</font>:<font color="#D0CFCC"> </font><font color="#12488B">0</font>,
<font color="#D0CFCC">        </font><font color="#2A7BDE">&quot;timestamp&quot;</font>:<font color="#D0CFCC"> </font><font color="#A2734C">&quot;2024-10-23T00:04:10.26&quot;</font>
<font color="#D0CFCC">    </font>},
</pre>

<pre><font color="#26A269"><b>➜  </b></font><font color="#2AA1B3"><b>apt.conf.d</b></font> http GET https://temps-attente-en-agence.p.rapidapi.com/agences/4151/historique debut==&quot;2024-10-23T00:00:00&quot; fin==&quot;2024-10-24T00:00:00&quot; x-rapidapi-host:&quot;temps-attente-en-agence.p.rapidapi.com&quot; x-rapidapi-key:&quot;bf68e0a1eb58955&quot;
<font color="#12488B">HTTP</font>/<font color="#12488B">1.1</font> <font color="#12488B">200</font> <font color="#2AA1B3">OK</font>
<font color="#2AA1B3">Connection</font>: keep-alive
<font color="#2AA1B3">Content-Type</font>: application/json;charset=UTF-8
<font color="#2AA1B3">Date</font>: Thu, 24 Oct 2024 02:20:05 GMT
<font color="#2AA1B3">Server</font>: RapidAPI-1.2.8
<font color="#2AA1B3">Transfer-Encoding</font>: chunked
<font color="#2AA1B3">X-RapidAPI-Region</font>: AWS - ap-southeast-2
<font color="#2AA1B3">X-RapidAPI-Request-Id</font>: c9311bc673a3faeb0cd0f57557f2ba6089962d6b6c0bc7257efcfd3e45ac05c4
<font color="#2AA1B3">X-RapidAPI-Version</font>: 1.2.8
<font color="#2AA1B3">X-RateLimit-rapid-free-plans-hard-limit-Limit</font>: 500000
<font color="#2AA1B3">X-RateLimit-rapid-free-plans-hard-limit-Remaining</font>: 499969
<font color="#2AA1B3">X-RateLimit-rapid-free-plans-hard-limit-Reset</font>: 2498075
<font color="#2AA1B3">set-cookie</font>: LB_BACKEND_ID=1; path=/
<font color="#2AA1B3">strict-transport-security</font>: max-age=31536000; includeSubdomains; preload
<font color="#2AA1B3">x-content-type-options</font>: nosniff

[
<font color="#D0CFCC">    </font>{
<font color="#D0CFCC">        </font><font color="#2A7BDE">&quot;realMaxWaitingTimeMs&quot;</font>:<font color="#D0CFCC"> </font><font color="#12488B">0</font>,
<font color="#D0CFCC">        </font><font color="#2A7BDE">&quot;timestamp&quot;</font>:<font color="#D0CFCC"> </font><font color="#A2734C">&quot;2024-10-23T00:00:17.779&quot;</font>
<font color="#D0CFCC">    </font>},
<font color="#D0CFCC">    </font>{
<font color="#D0CFCC">        </font><font color="#2A7BDE">&quot;realMaxWaitingTimeMs&quot;</font>:<font color="#D0CFCC"> </font><font color="#12488B">0</font>,
<font color="#D0CFCC">        </font><font color="#2A7BDE">&quot;timestamp&quot;</font>:<font color="#D0CFCC"> </font><font color="#A2734C">&quot;2024-10-23T00:02:09.214&quot;</font>
<font color="#D0CFCC">    </font>},
<font color="#D0CFCC">    </font>{
<font color="#D0CFCC">        </font><font color="#2A7BDE">&quot;realMaxWaitingTimeMs&quot;</font>:<font color="#D0CFCC"> </font><font color="#12488B">0</font>,
<font color="#D0CFCC">        </font><font color="#2A7BDE">&quot;timestamp&quot;</font>:<font color="#D0CFCC"> </font><font color="#A2734C">&quot;2024-10-23T00:04:10.26&quot;</font>
<font color="#D0CFCC">    </font>},
</pre>

**Comment by morgancarre** [comment]
C'est bon ça marche de mon côté pour cette date : 
![image](https://github.com/user-attachments/assets/ddc1ea1c-3eb3-41a0-921f-58336a1f0ae2)
 
 Mais j'avais bien mis ma clé API je l'avait juste censuré 
 
 Par contre j'ai réessayé avec la date que j'ai utilisé debut=="2024-08-10T12:15:50" fin=="2024-08-10T15:15:50" et ça me fait pareil : 
 
 ```shell
 http GET https://temps-attente-en-agence.p.rapidapi.com/agences/4151/historique debut=="2024-08-10T12:15:50" fin=="2024-08-10T15:15:50" x-rapidapi-host:"temps-attente-en-agence.p.rapidapi.com" x-rapidapi-key:"5571b9e79dmshe4f798cfda95f15p14a7c7jsncead51fc3d97"
HTTP/2 200 OK
Content-Type: application/json;charset=UTF-8
Date: Thu, 24 Oct 2024 03:01:20 GMT
Server: RapidAPI-1.2.8
Set-Cookie: LB_BACKEND_ID=1; path=/
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Content-Type-Options: nosniff
X-Rapidapi-Region: AWS - ap-southeast-2
X-Rapidapi-Request-Id: a693e5884654076ebfe1645f4835c88e181bee2f010bb041cd5d2305d8b07f30
X-Rapidapi-Version: 1.2.8
X-Ratelimit-Rapid-Free-Plans-Hard-Limit-Limit: 500000
X-Ratelimit-Rapid-Free-Plans-Hard-Limit-Remaining: 499968
X-Ratelimit-Rapid-Free-Plans-Hard-Limit-Reset: 2505998

[]
```

**Comment by morgancarre** [comment]
Oui enfaite j'essayé de faire un appel pour le 10 aout et c'est un samedi, l'agence était juste fermé enfaite 😅​
Sinon tout était bon , merci !

**Comment by Supervinh** [comment]
> Oui enfaite j'essayé de faire un appel pour le 10 aout et c'est un samedi, l'agence était juste fermé enfaite 😅​Sinon tout était bon , merci !

Aucun soucis, mais attention les résultats donnés par rapidapi sont en UTC et pas en UTC+11, donc là il t'a renvoyé les résultats pendant la nuit (donc aucun parce qu'elle était fermée effectivement).
Est-ce que vous pouvez me confirmer que vous pouvez tout de même avancer sur le projet en utilisant killercoda/rapidapi le temps que APIGEE soit fonctionnel sur ce endpoint ?

**Comment by morgancarre** [comment]
> > Oui enfaite j'essayé de faire un appel pour le 10 aout et c'est un samedi, l'agence était juste fermé enfaite 😅​Sinon tout était bon , merci !
> 
> Aucun soucis, mais attention les résultats donnés par rapidapi sont en UTC et pas en UTC+11, donc là il t'a renvoyé les résultats pendant la nuit (donc aucun parce qu'elle était fermée effectivement). Est-ce que vous pouvez me confirmer que vous pouvez tout de même avancer sur le projet en utilisant killercoda/rapidapi le temps que APIGEE soit fonctionnel sur ce endpoint ?

Oui j'arrive à avancer avec rapidapi

**Comment by adriens** [comment]
Top, on va faire de notre mieux pour fixer sur APIGEE afin que l'on puisse l'utiliser lors de la soutenance.
👉  Si pas prêt à temps, je valoriserai la qualité de la collab' autour de la remontée de ce bug car c'est un travail très important et pas évident.

**Comment by Supervinh** [comment]
@morgancarre @MalcolmBrt Hello, je viens avec des ~~bonnes ?🥴~~ nouvelles. J'ai pu avancer sur le problème de l'endpoint et je devrais avoir bientôt un fix utilisable pour votre projet, je vous tiens au courant dès que c'est finalisé. (Au passage, @adriens m'a montré un peu votre projet et il a l'air super)

**Comment by adriens** [comment]
Yes j'ai montré la PR avec l'histogramme coloré de l historique et oui... c bien cool ;-p

**Comment by MalcolmBrt** [comment]
> @morgancarre @MalcolmBrt Hello, je viens avec des ~bonnes ?🥴~ nouvelles. J'ai pu avancer sur le problème de l'endpoint et je devrais avoir bientôt un fix utilisable pour votre projet, je vous tiens au courant dès que c'est finalisé. (Au passage, @adriens m'a montré un peu votre projet et il a l'air super)

okay super merci

**Comment by adriens** [comment]
Good job la team c une super collaboration 
Je ne manquerai pas de relever cela le jour de la soutenance et dans l'évaluation
