### ISSUE TITLE
🕙 Changer timezone API Killercoda

### ISSUE THREAD

**Issue by MalcolmBrt** [adriens/temps-attente-streamlit#51]
Pour changer le fuseau horaire de l'API, il faut modifier la commande de lancement du conteneur.

Au lieu de lancer le conteneur comme ça :
```shell
docker run -d --rm -p 8080:8080 optnc/opt-temps-attente-agences-api:latest
```

Il faut inclure la variable d'environnement pour le fuseau horaire :
```shell
docker run -e TZ=Pacific/Noumea -d --rm -p 8080:8080 optnc/opt-temps-attente-agences-api:latest
```
On obtiens le résultat suivant :

**Avant :**

![image](https://github.com/user-attachments/assets/6fac9757-7f59-4c89-a3b8-d9b77b05bf77)

**Après :**

![image](https://github.com/user-attachments/assets/646a6e9b-c0dd-4d57-afdb-0be8bbeb518d)

**Comment by adriens** [comment]
:ok_hand: @Supervinh on fera ça rapido, c'est pas compliqué

**Comment by Supervinh** [comment]
@MalcolmBrt C'est bon pour killercoda, la timezone a bien été modifiée ! Pour tes prochaines issues n'hésite pas à lier d'autre issues pour que les gens sachent de quoi tu parles, par exemple avec ça :

- https://github.com/adriens/temps-attente-streamlit/issues/50#issuecomment-2428151294

**Comment by adriens** [comment]
Yes, ainsi on peut collaborer même si on ne travaille pas sur les mêmes créneaux en synchrone.
@Supervinh a travaillé sur l'API j'espère qu'on aura des good news pour vous prochainement :crossed_fingers:
