### ISSUE TITLE
Bug lors de sélection d'une commune

### ISSUE THREAD

**Issue by MalcolmBrt** [adriens/temps-attente-streamlit#53]
Parfois lorsqu'on essaie de sélectionner une commune, celle-ci n'est pas sélectionnée.
# Voir ci-dessous
[Capture vidéo du 2024-10-24 19-18-09.webm](https://github.com/user-attachments/assets/02cad618-1156-4aeb-b76a-a2a8bbe4075b)

**Comment by adriens** [comment]
Tu pourras tenter un drop au format `mp4` afin que l'on puisse avor le preview direct dans l'issue ?

![image](https://github.com/user-attachments/assets/7aec01d4-6530-4c3a-b7dd-1cfcd29f8c80)

**Comment by MalcolmBrt** [comment]
Ok c'est modifié, je sais pas pourquoi mais le preview ne s'affiche que quand je met un titre au dessus.

**Comment by adriens** [comment]
C'est génial car du coup même depuis mon mobilis je peux voir

**Comment by adriens** [comment]
Btw toi aussi tu es en galère de recherche de stage ? Comme @morgancarre ?

**Comment by MalcolmBrt** [comment]
Non moi j'ai trouvé un stage a l'opt

**Comment by adriens** [comment]
Chez qui ? Payé?

**Comment by MalcolmBrt** [comment]
A la DSI justement ahah avec Sabrina Verolle. Et non payé.

**Comment by adriens** [comment]
C une super équipe tu vas t'éclater

**Comment by adriens** [comment]
Ok je tente un truc pour @morgancarre sur le même modèle alors
Je demande semaine prochaine à mon manager

**Comment by morgancarre** [comment]
Super merci beaucoup , je croise les doigts 🤞​

**Comment by adriens** [comment]
De ton côté dis moi ce qui te fait vibrer en dev.
J'ai des trucs mais comme ça je saurai up peu plus

**Comment by morgancarre** [comment]
J'aime bien le dev web back end ou front end mais je suis quand même bien débutant dans ce domaine

**Comment by adriens** [comment]
Ok.
Je vais te proposer un projet progressif et innovant sur ce sujet
Tu pourras valoriser facilement 
Envoie moi un mail de rappel stp sur mon mail pro que je n'oublie pas

**Comment by morgancarre** [comment]
ok je viens de te l'envoyé
