### ISSUE TITLE
🎦 Démo vidéo au format mp4

### ISSUE THREAD

**Issue by MalcolmBrt** [adriens/temps-attente-streamlit#58]
Produire une démo vidéo de l’interface web présentant les temps d’attente pour les agences OPT.
La vidéo doit être simple, claire et accessible pour un public général, dans le but d’être diffusée par l’OPT sur la plateforme dev.to/optnc.
Durée maximale : 20 minutes.

**Comment by adriens** [comment]
Inclure comment installer et lancer l application... choper une api key etc...

**Comment by MalcolmBrt** [comment]
J'ai fais la vidéo, je l'envoie comment ? @adriens

**Comment by adriens** [comment]
Via un dropbox ou Google drive ? Ou autre système de partage de ton choix

**Comment by MalcolmBrt** [comment]
Ok j'ai upload sur wetransfer : https://wetransfer.com/downloads/ae95b3ff006a9b656d33719ffad0159320241124021437/130c2a8a4baedcb8ca9c75c0fe354cdf20241124021507/a6401b?t_exp=1732673677&t_lsid=a2d670be-af19-4b44-9dc2-8eef4b720fce&t_network=email&t_rid=ZW1haWx8Njc0MjhjMTBiNjM1NTFjNmY2ZThiZTJh&t_s=download_link&t_ts=1732414507&trk=TRN_TDL_01

**Comment by adriens** [comment]
Top
Je regarde ça tout à l'heure

**Comment by adriens** [comment]
Download en cours :long_drum:

**Comment by adriens** [comment]
Visionnage en cours, et top le son :+1:

**Comment by adriens** [comment]
## Feedbacks

- Très bien le rappel du rôle du Lead Dev
- Impeccable le flow du projet, très clair :ok_hand: 
- Architecture :ok_man: 
- Très bien les commenatires sur la slide de la jauge
- Quant tu parles de l'extension `.py`, tu pourras dire phonétiquement : _"point paille"_
- **:point_up:  Pour la slide du dataviz, le jour de la soutenance** tu pourras accentuer sur l'intéret de disposer d'une tendance vs. un temps instantané :thinking: ... c'est vraiment ce qui fait la différence avec ce projet
- **:point_up: Sur la slide où tu parles des hueres non ouvertes, le jour J mentionnes** que du coup, tu ne fais pas appel inutilement à l'API
- :clap: sur l'install from scratch : aller sur la repo et cloner c top :+1: 
- C super cool de switcher sur une autre activité pendant que tu buildes
- :point_up: Pas grave dans ce contexte mais normalement tu ne devrais pas avoir besoin d'être `root` pour builder ton image
- :ok_man: Top le déroulé de la connexion à APIGEE :clap: 
- :ok_man: Top la cration d'une nouvelle appli sur APIGEE
- :ok_man: Très bien les commentaires sur comment tu te logges sur rapidAPI vs. APIGEE
- :ok_hand: Cool que tu aies édité avec `vim` :nerd_face: 

## Demande nouvelle video

La video est top mais du coup, on ne voit pas le produit vivre car c'est le week-end : tu pourras faire un petit shoot video commenté en journée qu'on voit la tête du produit final ? Je pense qu'en une minute c'est tranquille et comme ça on reste sous les 20' :sunglasses:  @MalcolmBrt 
:point_right: Je rajouterai cette partie à la fin de la video que tu as livrée ce jour, je ferai le montage nécessaire pour coller les deux en une video unique

**Comment by adriens** [comment]
btw @MalcolmBrt 
![image](https://github.com/user-attachments/assets/ce8df8e9-ff55-4e07-bd1c-a6b024522977)

**Comment by morgancarre** [comment]
Super cool la vidéo :)

**Comment by adriens** [comment]
> Super cool la vidéo :)

Yes, très bon rythme, calme, très bon son, conenu bien clean et commenté. Il ne reste plus que voir un peu de la donnée genre en fin de journée sur deux ou trois agences et c de la :bomb: :100:

**Comment by MalcolmBrt** [comment]
D'accord je prends en compte ces conseils pour la soutenance, j'avais pensé à faire une petite vidéo en semaine mais comme je suis en stage c'est un peu compliqué pour les horaires

**Comment by adriens** [comment]
> D'accord je prends en compte ces conseils pour la soutenance,

Yes, et on a la soutenance à blanc en plus :+1: 

> j'avais pensé à faire une petite vidéo en semaine mais comme je suis en stage c'est un peu compliqué pour les horaires

yes, je vois. Sinon, semaine pro, tu pourras prendre sur le créneau de soutenance à blanc ou demander un créneau de 15' à ton reponsable de stage, ça devrait suffire. Ou alors tu vires l'option qui n'afiche rien quand les agences sont fermées et du coup c'est jouable le soir t'en dis quoi ?

**Comment by MalcolmBrt** [comment]
Ouai je pense que je vais temporairement désactiver l'option qui n'affiche rien quand les agences sont fermées. Je vais faire ça demain soir

**Comment by adriens** [comment]
yes, et puis...fonctionnellement c'est intéressant de pouvoir revisionner le bilan de la jounée.... je n'y pense que maintenant en fait :sweat_smile: 

:bulb: E fait, on pourrait préciser que les agences sont fermées mais malgré tout afficher l'histo du jour courant

**Comment by MalcolmBrt** [comment]
Je voulais faire la vidéo démo de l'application mais on dirait qu'il y a un petit problème avec l'API :
![image](https://github.com/user-attachments/assets/069c904b-318f-4930-b198-b7470f252b4b)

**Comment by adriens** [comment]
Quel endpoint ?

**Comment by MalcolmBrt** [comment]
C'est l'endpoint historique de l'api rapidapi

**Comment by adriens** [comment]
OK, essaie de faire tourner l'API en local, avec un peu de chance ça pourra marcher pour ce soir : https://hub.docker.com/r/optnc/opt-temps-attente-agences-api

En parallèle, tu peux faire une issue de type incident à @Supervinh :pray: On s'y collera demain matin

**Comment by MalcolmBrt** [comment]
Ça ne semble pas fonctionner en local non plus
![image](https://github.com/user-attachments/assets/fec0b9a1-99b5-438f-a5cc-6a304655ae82)

Voici l'issue incident : 
- #61

**Comment by adriens** [comment]
Ok.
Bon au moins c'est homogène 
Ça sent pas bon. On regarde ça demain avec @Supervinh 
Merci pour l'issue dédiée

**Comment by Supervinh** [comment]
@MalcolmBrt En effet il semblerait que l'agence 4153 ne possède pas de données de temps (pourquoi, on ne sait pas encore, peut être à cause des évènements qui ont fermé l'agence). Le mieux serait que vous passiez sur l'agence principale (1151) qui possède bien des données (j'ai vérifié de mon côté). En revanche si cette agence ne renvoie rien, là c'est qu'on a un gros problème. 
En tout cas bien vu pour avoir remonté l'erreur, ça va nous servir pour la suite :+1:

**Comment by adriens** [comment]
Yes, on investigue dessus, mais du coup, plus de blocage sur la démo video des historiques en live :rocket:

**Comment by MalcolmBrt** [comment]
J'ai fais le reste de la vidéo hier soir mais j'ai complètement oublié de l'upload. Je le fait ce soir.

**Comment by MalcolmBrt** [comment]
Voici la vidéo complète : https://we.tl/t-0P1jwkrQdJ

**Comment by adriens** [comment]
je suis entrain de la :arrow_down:

**Comment by adriens** [comment]
@MalcolmBrt tu as bien revké les clés que tu as montrées en claire dans la video ?

**Comment by adriens** [comment]
:exploding_head: impressionant le rush !!!!

![image](https://github.com/user-attachments/assets/8d6d24b6-13a1-4353-af71-ae77a9321753)

**Comment by adriens** [comment]
Très intéressant de montrer un peu de variété 
![image](https://github.com/user-attachments/assets/d7e0deda-816d-4cad-b102-ea1ac6520c35)

@MalcolmBrt ça serait super cool de le rajouter pour montrer que les porfils sont très très différent

**Comment by adriens** [comment]
Ben c'est :ok: j'uploade :rocket:

**Comment by adriens** [comment]
![image](https://github.com/user-attachments/assets/4e919a7c-102f-452f-a6f8-2d37f84fc744)

il me reestera à couper, faire la cover, indexer etc... c'est dans le pipe de mon côté :+1:

**Comment by MalcolmBrt** [comment]
> @MalcolmBrt tu as bien revké les clés que tu as montrées en claire dans la video ?

Oui je viens de le faire
