### ISSUE TITLE
:books:  Supports de soutenance

### ISSUE THREAD

**Issue by adriens** [adriens/temps-attente-streamlit#6]
- [x] Etudiants::Rapport au format pdf
- [x] Etudiants::Support de présentation ppt au format pdf
- [x] Révisions et feedback sur les supports
- [x] Etudiants::Video de demo < 20' au format mp4
- [x] @adriens ::Fournir évaluation à l'équipe pédagogique

**Comment by MalcolmBrt** [comment]
Bonjour @adriens, nous avons commencé la rédaction du rapport mais on ne sait pas vraiment quel temps adopté. Mieux vaut il parler au présent ou au passé ?

**Comment by adriens** [comment]
Top le ticket

**Comment by adriens** [comment]
> Bonjour @adriens, nous avons commencé la rédaction du rapport mais on ne sait pas vraiment quel temps adopté. Mieux vaut il parler au présent ou au passé ?

Selon vous qu'est-ce qui fait le plus sens... sachant que le jour J le produit sera considéré comme livré... Je vous laisse deviner le bon temps

**Comment by adriens** [comment]
Il ne reste plus que l'évaluation du rapport il me semble non @MalcolmBrt ?

**Comment by MalcolmBrt** [comment]
Oui c'est ça

**Comment by adriens** [comment]
> Oui c'est ça

Tu as le formulaire de base de ton côté ?

**Comment by MalcolmBrt** [comment]
Oui le voici en pièce jointe, il y a également la fiche d'évaluation global du projet incluse.
[Evaluation Tuteur Projet Tutoré.pdf](https://github.com/user-attachments/files/17963289/Evaluation.Tuteur.Projet.Tutore.pdf)

Pour informations, voici les modalités de notations : 
![image](https://github.com/user-attachments/assets/dbdd6b11-b866-44d3-89bb-d480bc071ca3)

**Comment by adriens** [comment]
OKi ça roule :+1:

**Comment by adriens** [comment]
Rédaction des évalutaion en cours...

**Comment by adriens** [comment]
Evaluations terminées, je les communique dans la foulée :rocket: @morgancarre @MalcolmBrt

**Comment by adriens** [comment]
:clap: @MalcolmBrt @morgancarre :point_down: 

![image](https://github.com/user-attachments/assets/dae8c165-2637-46a0-bfd6-e660dcef2383)
![image](https://github.com/user-attachments/assets/c316bcd5-ad80-4de9-920d-b00ade04f5c8)

**Comment by MalcolmBrt** [comment]
Wow super merci 😊

**Comment by adriens** [comment]
Yes, merci c'était bien top comme collab' :sunglasses:

**Comment by morgancarre** [comment]
Super notes, merci 👌​

**Comment by adriens** [comment]
Bien joué les gars ct bien cool
