### ISSUE TITLE
:rotating_light: Historique temps d'attente vide :grey_question: 

### ISSUE THREAD

**Issue by MalcolmBrt** [adriens/temps-attente-streamlit#61]
L'endpoint historique de l'API des temps d'attente sur [RapidAPI](https://rapidapi.com/opt-nc-opt-nc-default/api/temps-attente-en-agence) retourne constamment une liste vide : 
```shell
http https://temps-attente-en-agence.p.rapidapi.com/agences/4153/historique?debut=2024-11-25T03:30:00 x-rapidapi-host:temps-attente-en-agence.p.rapidapi.com x-rapidapi-key:[Clé RapidAPI]
``` 
![image](https://github.com/user-attachments/assets/069c904b-318f-4930-b198-b7470f252b4b)

En local avec l'[image Docker](https://hub.docker.com/r/optnc/opt-temps-attente-agences-api) le problème semble être le même :
```shell
http localhost:8080/agences/4153/historique?debut=2024-11-25T03:30:00
```
![image](https://github.com/user-attachments/assets/cc9cf335-256b-4f47-be69-af493d8c5879)

**Comment by adriens** [comment]
@Supervinh  y'a un petite douille....

**Comment by adriens** [comment]
Issue de support interne crée :+1:

**Comment by Supervinh** [comment]
[Même réponse ici](https://github.com/adriens/temps-attente-streamlit/issues/58#issuecomment-2499019398)

@MalcolmBrt En effet il semblerait que l'agence 4153 ne possède pas de données de temps (pourquoi, on ne sait pas encore, peut être à cause des évènements qui ont fermé l'agence). Le mieux serait que vous passiez sur l'agence principale (1151) qui possède bien des données (j'ai vérifié de mon côté). En revanche si cette agence ne renvoie rien, là c'est qu'on a un gros problème. 
En tout cas bien vu pour avoir remonté l'erreur, ça va nous servir pour la suite :+1:

**Comment by MalcolmBrt** [comment]
Ah c'est vrai que j'aurai du regarder pour d'autres agences. J'ai pris une agence au hasard.

**Comment by adriens** [comment]
> Ah c'est vrai que j'aurai du regarder pour d'autres agences. J'ai pris une agence au hasard.

Oui, mais c'est super car grâce à toi on est tombé sur une anomalie, donc c'est encore une fois du super boulot @MalcolmBrt :+1:
