### ISSUE TITLE
:student: Soutenance finale

### ISSUE THREAD

**Issue by adriens** [adriens/temps-attente-streamlit#7]
- [x] Planifier soutenance à blanc à l'OPT
- [x]  Avoir lieu, date et heure de la soutenance UNC
- [x] Envoyer les invitations OPT-NC
- [x] Planfiier soutenance à blanc
- [x] Réaliser soutenance à blanc
- [x] Réaliser la soutenance
- [x] 📸  Shooter et dropper des photos pour souvenirs

**Comment by adriens** [comment]
:wave: @MalcolmBrt , j'ai besoin de ces éléments afin de m'assurer que je serai bien dispo sur les dits créneaux : je ne pourrai pas forcément me rendre dispo au dernie rmoment, j'ai besoin que ce soit planifié

**Comment by MalcolmBrt** [comment]
Bonjour @adriens, pour la date de la soutenance on a une date "prévisionnelle" au 29/11, je l'ai appliqué à la milestone.
C'est Morgan qui se charge du support de soutenance, je vais lui demander où il en est. Dès qu'il a fini je m'occupe de la vidéo démo.

**Comment by adriens** [comment]
Une date prévisionnnlle, et sur une journée complète ne me permet pas de m'organiser en entreprise : je ne peux pas verrouiller une journée entière pour une soutenance de 30' : pex-tu stp te rapprocher de l'équipe pédagogique ?

**Comment by adriens** [comment]
> C'est Morgan qui se charge du support de soutenance, je vais lui demander où il en est.

Je devrais avoir des news sur l'issue dédiée mais je ne vois rien 
- https://github.com/adriens/temps-attente-streamlit/issues/56

![image](https://github.com/user-attachments/assets/5a727586-e85f-4b55-99c2-de9ba8dd8717)

**Comment by MalcolmBrt** [comment]
> Une date prévisionnnlle, et sur une journée complète ne me permet pas de m'organiser en entreprise : je ne peux pas verrouiller une journée entière pour une soutenance de 30' : pex-tu stp te rapprocher de l'équipe pédagogique ?

D'accord, je vois ça avec l'équipe pédagogique et je te tiens au courant dès que j'ai des nouvelles.

**Comment by adriens** [comment]
Top, merci.

**Comment by adriens** [comment]
Soutenance à blanc planifiée à mercredi prochain @morgancarre @MalcolmBrt  : 

![image](https://github.com/user-attachments/assets/db84b8e4-43cc-465c-a31b-5cc925dc6fb3)


:point_right: Des news @MalcolmBrt pour la planif Date/heure de la soutenance finale?

**Comment by MalcolmBrt** [comment]
Non aucune... Je viens de renvoyer un mail à Claire LESCHI

**Comment by MalcolmBrt** [comment]
Voici les horaires : 
![image](https://github.com/user-attachments/assets/2c8009ff-b7d0-489b-92de-e68004064b31)

**Comment by adriens** [comment]
Je vais préparer les agenda des collègues

**Comment by adriens** [comment]
Euh...il manque la date non ?

**Comment by MalcolmBrt** [comment]
C'est le 28

**Comment by adriens** [comment]
🚀 Invitations envoyées

![image](https://github.com/user-attachments/assets/303f04fa-f523-41e2-896a-a4e390c0fbcf)

**Comment by adriens** [comment]
![image](https://github.com/user-attachments/assets/66ab82a9-8036-4646-9b01-044939f5cc33)

**Comment by morgancarre** [comment]
@adriens je t'ai envoyé un mail sur ton mail pro par rapport à mon stage , à tu eu le temps de le lire ?

**Comment by adriens** [comment]
Yes et d'y répondre même ;-p

**Comment by adriens** [comment]
Soutenance à blanc effectuée cet aprem avec visite du GLIA et le backend avec @Supervinh @MalcolmBrt et @morgancarre 
SUpers feedbacks de toute la team du GLIA :pray: :clap: 

:point_right: Rdv demain 08h00 salle S2 pour la soutenance officielle :rocket: Let's GO @MalcolmBrt @morgancarre

**Comment by adriens** [comment]
![0f91de79-1bde-43ee-9909-0574c26e0609 (1)](https://github.com/user-attachments/assets/a43e0645-f72c-4828-8f6c-e694b314f5e5)
![0f91de79-1bde-43ee-9909-0574c26e0609](https://github.com/user-attachments/assets/180e7dab-708d-4cc1-b001-9297b663eba5)
![3c54d238-cccf-415f-8fc2-69add539f763](https://github.com/user-attachments/assets/ecd9005f-8c78-488c-8948-505c181d41bd)
![4c06c938-7d0a-4edc-be0d-cdbd5d1d3af0](https://github.com/user-attachments/assets/9e6a35af-2f51-4d7c-9952-cc8de1ebc218)
![34b88f9b-ba91-448b-ab25-cad76d06ac52](https://github.com/user-attachments/assets/94e4c367-f9cd-4445-b0b5-dd3c33832b33)
![80ef535a-c830-4db3-a07b-4009e64bc748](https://github.com/user-attachments/assets/1cfa1a11-b7cd-4005-b67b-3f182d3d3a32)

**Comment by adriens** [comment]
## linkedIn

[post](https://www.linkedin.com/posts/adrien-sales_api-architect-quarkus-activity-7268012732291907585-ZNk5?utm_source=share&utm_medium=member_desktop)

![Image](https://github.com/user-attachments/assets/3f310d27-3407-407c-8112-40939e737993)


## tweet

[tweet](https://x.com/rastadidi/status/1862247586411028971)

![Image](https://github.com/user-attachments/assets/23b5374a-ea92-448d-9394-f642086030f6)
