### ISSUE TITLE
:shield: linter le python avec la CI et une GH ACtions/`ruff`

### ISSUE THREAD

**Issue by adriens** [adriens/temps-attente-streamlit#9]
# :grey_question: Contexte

Dans un contexte de dev Open Source et collaboratif, il est capital de protéger votre code source.

Pour cela, il faut le linter.

# :dart: Actions

- [x] Lire et comprendre [Automate Python Linting and Code Style Enforcement with Ruff and GitHub Actions](https://dev.to/ken_mwaura1/automate-python-linting-and-code-style-enforcement-with-ruff-and-github-actions-2kk1)
- [x] Regarder [comment intégrer ruff aux Gh ACtions](https://docs.astral.sh/ruff/integrations/)
- [x] Implémenter sur la CI
- [x] Valider que tout merge de code/PR passe impérativement par le lint

# :bookmark: Ressources

- https://github.com/astral-sh/ruff
- https://docs.astral.sh/ruff/
- https://github.com/ChartBoost/ruff-action
- https://docs.astral.sh/ruff/integrations/

**Comment by MalcolmBrt** [comment]
Petite question, je dois faire une branche pour l'ajout de la CI ?

**Comment by adriens** [comment]
Yes, c toujour mieux.
A minima, toujours passer par une PR sur une branche temporaire pour pouvoir envoyer sur `main`

**Comment by adriens** [comment]
Ca permet de voir les déclencjements, c'est top pour apprendre :+1:

**Comment by adriens** [comment]
:bulb: -oublie pas de citer l'issue dans tes messages de commits, comme ça tu les verras relier aux issues concernées

**Comment by adriens** [comment]
:+1:
